"""Revision from model Document

Revision ID: 593d6f168aed
Revises: 5e7cc29c6182
Create Date: 2025-03-09 23:41:01.534493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593d6f168aed'
down_revision = '5e7cc29c6182'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###    
    op.drop_index('ix_documents_chunk_id', table_name='documents')
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.drop_column('documents', 'chunk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chunk_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.create_index('ix_documents_chunk_id', 'documents', ['chunk_id'], unique=False)   
    # ### end Alembic commands ###
