"""Revision from model Documento

Revision ID: 5e7cc29c6182
Revises: 2d80ad401c6d
Create Date: 2025-03-09 23:18:48.236500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e7cc29c6182'
down_revision = '2d80ad401c6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('chunk_id', sa.String(length=200), nullable=True))    
    op.create_index(op.f('ix_documents_chunk_id'), 'documents', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_chunk_id'), table_name='documents')    
    op.drop_column('documents', 'chunk_id')
    # ### end Alembic commands ###
